import numpy as np
import pandas as pd

years = np.random.randint(2010, 2024, size=(100000, 1))
print(years)
print(len(years))
sales = np.random.randint(500, 1500, size=(100000, 1))
viruchka = np.random.randint(50000, 150000, size=(100000, 1))
print('слеили 3 массива')
data = np.concatenate((years, sales, viruchka), axis=1)
print(data)

# newdata = data[data[:,0]==2018]
# sum18sales = np.sum(newdata[:,1])
# sum18vir = np.sum(newdata[:,2])
# print(newdata)
# print(sum18sales)
# print(sum18vir)
print('**************************************************************************************')
print('1 способ решения задачи')
print('сортируем массив по годам')
sorted_array = data[data[:, 0].argsort()]
print(sorted_array)
print('смотрим уникальные значения годов в отсортированном массиве')
unique_values, unique_indices  = np.unique(sorted_array[:, 0], return_index=True)
print(unique_values)
print('Для каждого года формируем сумму продаж и суммарную выручку')
result_array = []
for i in range(len(unique_values)):
    group = sorted_array[sorted_array[:,0]==unique_values[i]]
    sum_sales = np.sum(group[:, 1])
    sum_vir = np.sum(group[:, 2])
    # print(group)
    # print(sum_sales)
    # print(sum_vir)
    result_row = np.hstack((unique_values[i], sum_sales, sum_vir))
    result_array.append(result_row)
print(result_array)
print('преобразуем полученный массив в массив numpy')
final_array = np.array(result_array)
print(final_array)
print('максимальные значения по столбцам')
maxs = np.max(final_array,axis=0)
print(maxs)
print('позиции максимумов')
numbers = np.argmax(final_array,axis=0)
print(numbers)
print('максимальное количество продаж',maxs[1],'в году',final_array[numbers[1]][0])
print('максимальная выручка',maxs[2],'в году',final_array[numbers[2]][0])
print('**************************************************************************************')
print('2 способ решения задачи')
df = pd.DataFrame(data)
print(df)
# print(df.columns)
# print(df.index)
df2 = df.groupby(0).sum()
print('Группируем датасет по годам')
print(df2)
# print(df2.columns)
# print(df2.index)
print('Максимальное количество продаж',df2[1].max(),'в году',df2.idxmax(axis="index")[1])
print('Максимальная выручка',df2[2].max(),'в году',df2.idxmax(axis="index")[2])

